services:
  backend:
    build:
      context: ./backend

    container_name: securedoc-backend

    ports:
      - "8080:8080"

    env_file:
      - .env

    restart: unless-stopped

    networks:
      - securedoc-network


networks:
  securedoc-network:
    driver: bridge